/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppNewCaseRouteImport } from './routes/_app.new-case'
import { Route as AppLocationsRouteImport } from './routes/_app.locations'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppAnalysisRouteImport } from './routes/_app.analysis'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewCaseRoute = AppNewCaseRouteImport.update({
  id: '/new-case',
  path: '/new-case',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisRoute = AppAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/analysis': typeof AppAnalysisRoute
  '/cases': typeof AppCasesRoute
  '/categories': typeof AppCategoriesRoute
  '/feedback': typeof AppFeedbackRoute
  '/locations': typeof AppLocationsRoute
  '/new-case': typeof AppNewCaseRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analysis': typeof AppAnalysisRoute
  '/cases': typeof AppCasesRoute
  '/categories': typeof AppCategoriesRoute
  '/feedback': typeof AppFeedbackRoute
  '/locations': typeof AppLocationsRoute
  '/new-case': typeof AppNewCaseRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analysis': typeof AppAnalysisRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/new-case': typeof AppNewCaseRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analysis'
    | '/cases'
    | '/categories'
    | '/feedback'
    | '/locations'
    | '/new-case'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analysis'
    | '/cases'
    | '/categories'
    | '/feedback'
    | '/locations'
    | '/new-case'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/analysis'
    | '/_app/cases'
    | '/_app/categories'
    | '/_app/feedback'
    | '/_app/locations'
    | '/_app/new-case'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-case': {
      id: '/_app/new-case'
      path: '/new-case'
      fullPath: '/new-case'
      preLoaderRoute: typeof AppNewCaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analysis': {
      id: '/_app/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AppAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalysisRoute: typeof AppAnalysisRoute
  AppCasesRoute: typeof AppCasesRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppNewCaseRoute: typeof AppNewCaseRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalysisRoute: AppAnalysisRoute,
  AppCasesRoute: AppCasesRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppNewCaseRoute: AppNewCaseRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
